<?php
require 'vendor/autoload.php';
use Dompdf\Dompdf;

session_start();


if (!isset($_SESSION['score'])) {
    echo "Error: Score is not set.";
    exit();
}


$name = $_SESSION['user'] ?? 'Guest';
$score = $_SESSION['score'] ?? 0;
$subject = $_SESSION['subject'] ?? 'N/A';
$difficulty = $_SESSION['difficulty'] ?? 'N/A';
$attempts = $_SESSION['attempts'] ?? 1;
$questions = $_SESSION['questions'] ?? [];
$totalQuestions = count($questions);


$html = "
<html>
<head>
<style>
    body {
        font-family: Arial, sans-serif;
        padding: 30px;
    }
    h1 {
        text-align: center;
        color: #438412;
    }
    .details {
        margin-top: 30px;
        font-size: 18px;
    }
    .details p {
        margin: 8px 0;
    }
    .footer {
        margin-top: 40px;
        text-align: center;
        font-size: 14px;
        color: #777;
    }
</style>
</head>
<body>
    <h1>Quiz Scorecard</h1>
    <hr>
    <div class='details'>
        <p><strong>Name:</strong> {$name}</p>
        <p><strong>Subject:</strong> {$subject}</p>
        <p><strong>Difficulty Level:</strong> {$difficulty}</p>
        <p><strong>Score:</strong> {$score} / {$totalQuestions}</p>
        <p><strong>Attempts:</strong> {$attempts}</p>
        <p><strong>Date:</strong> " . date('d-m-Y') . "</p>
    </div>
    <div class='footer'>
        Generated by QuizzSparks
    </div>
</body>
</html>
";

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream("Quiz_Scorecard_{$name}.pdf", ["Attachment" => true]);
?>
